apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-kuc
  namespace: argocd
spec:
  project: argo-project
  source:
    path: charts/argocd
    repoURL: 'https://github.com/jtmack6/argo-kuc.git'
    targetRevision: HEAD 
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
